// Code generated by ogen, DO NOT EDIT.

package ogen

// OperationName is the ogen operation name
type OperationName = string

const (
	TodosFilterGetOperation       OperationName = "TodosFilterGet"
	TodosGetOperation             OperationName = "TodosGet"
	TodosIDCompletePostOperation  OperationName = "TodosIDCompletePost"
	TodosIDDeleteOperation        OperationName = "TodosIDDelete"
	TodosIDGetOperation           OperationName = "TodosIDGet"
	TodosIDPatchOperation         OperationName = "TodosIDPatch"
	TodosIDPriorityPatchOperation OperationName = "TodosIDPriorityPatch"
	TodosIDReopenPostOperation    OperationName = "TodosIDReopenPost"
	TodosIDTagsDeleteOperation    OperationName = "TodosIDTagsDelete"
	TodosIDTagsPostOperation      OperationName = "TodosIDTagsPost"
	TodosPostOperation            OperationName = "TodosPost"
	UsersIDDeleteOperation        OperationName = "UsersIDDelete"
	UsersIDGetOperation           OperationName = "UsersIDGet"
	UsersPostOperation            OperationName = "UsersPost"
)
