// Code generated by ogen, DO NOT EDIT.
package ogen

type TodosFilterGetRes interface {
	todosFilterGetRes()
}

type TodosIDCompletePostRes interface {
	todosIDCompletePostRes()
}

type TodosIDDeleteRes interface {
	todosIDDeleteRes()
}

type TodosIDGetRes interface {
	todosIDGetRes()
}

type TodosIDPatchRes interface {
	todosIDPatchRes()
}

type TodosIDPriorityPatchRes interface {
	todosIDPriorityPatchRes()
}

type TodosIDReopenPostRes interface {
	todosIDReopenPostRes()
}

type TodosIDTagsDeleteRes interface {
	todosIDTagsDeleteRes()
}

type TodosIDTagsPostRes interface {
	todosIDTagsPostRes()
}

type TodosPostRes interface {
	todosPostRes()
}

type UsersIDDeleteRes interface {
	usersIDDeleteRes()
}

type UsersIDGetRes interface {
	usersIDGetRes()
}

type UsersPostRes interface {
	usersPostRes()
}
